name: CI
on:
  push:
    branches: ["main"]
jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: echo hello
        run: echo Hello!
  test:
    runs-on: ['self-hosted','demo']
    steps:
    - uses: actions/checkout@v3

    - name: test python file
      run: python3 test.py Amber
  build:
    runs-on: ['self-hosted','demo']
    steps:
      - uses: actions/checkout@v3

      - name: login docker hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $username -p $password
